http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://172.20.0.12:9091/api/verify?rd=https://auth.mydia.com
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

  # Configuration TLS avec tes certificats mkcert
  tls:
    certificates:
      - certFile: /etc/ssl/certs/live/mydia.com/fullchain.pem
        keyFile: /etc/ssl/certs/live/mydia.com/privkey.pem